name: Lint code with Ruff

on:
  push:
    branches: [ "master", "stable-[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "master", "stable-[0-9]+.[0-9]+" ]

jobs:
  lint:
    name: Lint code with Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"

      - name: Check rules
        run: "ruff check"

      - name: Check format
        run: "ruff format --check --diff"
